api_version: 3
name: test
description: NVIDIA FLARE sample project yaml file

participants:
  - name: site-48
    type: client
    org: ornl
  - name: site-47
    type: client
    org: ornl
  - name: site-46
    type: client
    org: ornl
  - name: site-45
    type: client
    org: ornl
  - name: site-44
    type: client
    org: ornl
  - name: site-43
    type: client
    org: ornl
  - name: site-42
    type: client
    org: ornl
  - name: site-41
    type: client
    org: ornl
  - name: site-40
    type: client
    org: ornl
  - name: site-39
    type: client
    org: ornl
  - name: site-38
    type: client
    org: ornl
  - name: site-37
    type: client
    org: ornl
  - name: site-36
    type: client
    org: ornl
  - name: site-35
    type: client
    org: ornl
  - name: site-34
    type: client
    org: ornl
  - name: site-33
    type: client
    org: ornl
  - name: site-32
    type: client
    org: ornl
  - name: site-31
    type: client
    org: ornl
  - name: site-30
    type: client
    org: ornl
  - name: site-29
    type: client
    org: ornl
  - name: site-28
    type: client
    org: ornl
  - name: site-27
    type: client
    org: ornl
  - name: site-26
    type: client
    org: ornl
  - name: site-25
    type: client
    org: ornl
  - name: site-24
    type: client
    org: ornl
  - name: site-23
    type: client
    org: ornl
  - name: site-22
    type: client
    org: ornl
  - name: site-21
    type: client
    org: ornl
  - name: site-20
    type: client
    org: ornl
  - name: site-19
    type: client
    org: ornl
  - name: site-18
    type: client
    org: ornl
  - name: site-17
    type: client
    org: ornl
  - name: site-16
    type: client
    org: ornl
  - name: site-15
    type: client
    org: ornl
  - name: site-14
    type: client
    org: ornl
  - name: site-13
    type: client
    org: ornl
  - name: site-12
    type: client
    org: ornl
  - name: site-11
    type: client
    org: ornl
  - name: site-10
    type: client
    org: ornl
  - name: site-9
    type: client
    org: ornl
  - name: site-8
    type: client
    org: ornl
  - name: site-7
    type: client
    org: ornl
  - name: site-6
    type: client
    org: ornl
  - name: site-5
    type: client
    org: ornl
  - name: site-4
    type: client
    org: ornl
  - name: site-3
    type: client
    org: ornl
  # Change the name of the server (frontier00114) to the Fully Qualified Domain Name
  # (FQDN) of the server, for example: frontier00114.example.com.
  # Ensure that the FQDN is correctly mapped in the /etc/hosts file.
  - name: localhost
    type: server
    org: ornl
    fed_learn_port: 8002
    admin_port: 8003
  - name: site-1
    type: client
    org: ornl
    # Specifying listening_host will enable the creation of one pair of
    # certificate/private key for this client, allowing the client to function
    # as a server for 3rd-party integration.
    # The value must be a hostname that the external trainer can reach via the network.
    # listening_host: site-1-lh
  - name: site-2
    type: client
    org: ornl
  - name: admin@ornl.gov
    type: admin
    org: ornl
    role: project_admin

# The same methods in all builders are called in their order defined in builders section
builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
    args:
      template_file:
        - master_template.yml
        - aws_template.yml
        - azure_template.yml
  - path: nvflare.lighter.impl.template.TemplateBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      # config_folder can be set to inform NVIDIA FLARE where to get configuration
      config_folder: config

      # scheme for communication driver (currently supporting the default, grpc, only).
      # scheme: grpc

      # app_validator is used to verify if uploaded app has proper structures
      # if not set, no app_validator is included in fed_server.json
      # app_validator: PATH_TO_YOUR_OWN_APP_VALIDATOR

      # when docker_image is set to a docker image name, docker.sh will be generated on server/client/admin
      # docker_image:

      # download_job_url is set to http://download.server.com/ as default in fed_server.json.  You can override this
      # to different url.
      # download_job_url: http://download.server.com/

      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        # if overseer_exists is true, args here are ignored.  Provisioning
        #   tool will fill role, name and other local parameters automatically.
        # if overseer_exists is false, args in this section will be used and the sp_end_point
        # must match the server defined above in the format of SERVER_NAME:FL_PORT:ADMIN_PORT
        # 
        overseer_exists: false
        args:
          sp_end_point: localhost:8002:8003

  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder
